name: Transform JSON to CSV - Team Info

on:
  push:
    paths:
      - 'json/ipl_match/**'
  workflow_dispatch:  # Allows manual triggering
  
  workflow_run:
    workflows: ["Process Team Data"]
    types: [completed]

jobs:
  transform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Convert line endings to Unix-style
        run: sed -i 's/\r$//' TeamInfo.py

      - name: Set execute permissions for TeamInfo.py
        run: chmod +x TeamInfo.py

      - name: Run TeamInfo.py Script
        run: python TeamInfo.py

      - name: Create csv directory if not exists
        run: mkdir -p csv

      - name: Move CSV files to csv directory
        run: mv *.csv csv/

      - name: Get current date and time
        id: timestamp
        run: echo "::set-output name=date::$(TZ=Asia/Kolkata date +'%Y-%m-%d %H:%M:%S')"

      - name: Commit and push changes
        run: |
          git config --global user.name "iadityak0188"
          git config --global user.email "iadhi6336@gmail.com"
          git add csv/
          git commit -m "Dataset updated at - $(echo ${{ steps.timestamp.outputs.date }}) (IST)" || echo "No changes to commit"
          git push --force https://github.com/iadityak0188/-cricket-dataset-extract.git main
        continue-on-error: true
